spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
    application:
        name: movie-rental
    datasource:
        url: jdbc:mysql://localhost:3306/movie-rental
        username: root
        password: "06062023"
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
